### ISSUE TITLE
Error with datetime in data.py

### ISSUE THREAD

**Issue by sklafg** [mikemountain/fantasy-football-scoreboard#11]
Hi,

I'm getting this error when I try to launch the program.

Traceback (most recent call last):
  File "main.py", line 27, in <module>
    data = Data(config)
  File "/home/pi/fantasy-football-scoreboard/data/data.py", line 25, in __init__
    self.refresh_start()
  File "/home/pi/fantasy-football-scoreboard/data/data.py", line 73, in refresh_                                     start
    start_delta = datetime.strptime("{} 20:20:00 EDT".format(self.config.opening                                     _day), "%Y-%m-%d %H:%M:%S %Z") - datetime.now()
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2020-09-10 20:20:00 EDT' does not match format '%Y-%m-%d                                      %H:%M:%S %Z'

**Comment by mikemountain** [comment]
Huh, that's really weird because the time should match-up perfectly, I verified it a few different ways... 

I'm going to push up a new version of the repo soon that has this stuff removed (I was working on adding draft features but life got in the way) and it's only used for the draft, so we can just get rid of it for now, so I'll close this once I push it up

**Comment by mikemountain** [comment]
@sklafg can you pull the master branch and give it another run?

**Comment by sklafg** [comment]
It works fine now. 
Well done, thanks!
