### ISSUE TITLE
ESPN?

### ISSUE THREAD

**Issue by PHI34Halladay** [mikemountain/fantasy-football-scoreboard#20]
Hi,
are there any indications that the ticker will feature espn driven leagues for the new season?

Really looking forward to it...

**Comment by mikemountain** [comment]
Hey man, should hopefully have ESPN (and Yahoo) added for this season coming up, barring any unforeseen setbacks

**Comment by PHI34Halladay** [comment]
That sounds phenomenal :)

Let me know if you need someone to test sth.

**Comment by morpherios** [comment]
... I have nothing to contribute other than to say I am irrationally thrilled to get to run this scoreboard for another season.  Such an awesome project.

**Comment by mikemountain** [comment]
ESPN is ready to be tested! There's a branch now, f/espn-and-yahoo, that will HOPEFULLY work. It still needs to be tested live, in game, since it's still before the season starts. I can't guarantee ANY robustness for now.

But if you want to be a ESPN guinea pig, I've added steps in the README on how to spin up ESPN for the board.

If one has currently used this project for sleeper before, they'll have to `git stash` before doing a `git fetch` and a `git checkout f/espn-and-yahoo`
