### ISSUE TITLE
How close to Yahoo integration

### ISSUE THREAD

**Issue by BillLehecka** [mikemountain/fantasy-football-scoreboard#7]
I love this idea. It’d be awesome to keep the scoreboard above my TV setup so I don’t have to keep glancing at my phone and it would extend my scoreboard usage that I’m currently using for MLB scores. However, I’m a Yahoo user through and through. How soon down the road is Yahoo integration?

**Comment by mikemountain** [comment]
Hey man, sorry for the delay in getting back to this - I recently just moved so pretty much everything came to a grinding halt. I won't have the Yahoo integration done by week 1 unfortunately; it's high in the priority list so I'll be trying to work at it but I can't promise anything anytime soon

**Comment by morpherios** [comment]
Brother you're good, you do you, life priorities and all that, 100 percent.

I actually didn't need help with yahoo integration, my question was simply
proper syntax for the command to display other teams in the board, I wanted
to quickly and easily send each team matchup to the chat by taking a
picture.

If you're busy legit no worries, I can do it manually through the
config.json for now.

Additionally if you have a PayPal or something that I can toss a donation
to please don't hesitate to let me know.  I would be happy to throw some $
towards a meal or to buy you a beer for your help.

**Comment by BillLehecka** [comment]
> Brother you're good, you do you, life priorities and all that, 100 percent. I actually didn't need help with yahoo integration, my question was simply proper syntax for the command to display other teams in the board, I wanted to quickly and easily send each team matchup to the chat by taking a picture. If you're busy legit no worries, I can do it manually through the config.json for now. Additionally if you have a PayPal or something that I can toss a donation to please don't hesitate to let me know. I would be happy to throw some $ towards a meal or to buy you a beer for your help.
> […](#)

Yeah, it was my question... :)

No rush. Just curious. Will be excited when it’s finally available right now I’m just using my Pi Scoreboard to remind me how much the Mets frustrate me.

**Comment by mikemountain** [comment]
only took me just under a full year but Yahoo is ready to be tested! There's a branch now, [f/espn-and-yahoo](https://github.com/mikemountain/fantasy-football-scoreboard/tree/f/espn-and-yahoo), that will HOPEFULLY work. It still needs to be tested live, in game, since it's still before the season starts. I can't guarantee ANY robustness for now.

**But** if you want to be a Yahoo guinea pig, I've added steps in the README on how to spin up Yahoo for the board.

If one has currently used this project for sleeper before, they'll have to `git stash` before doing a `git fetch` and a `git checkout f/espn-and-yahoo`

(ESPN doesn't work yet because I don't have access to a private league til Monday, but I reworked some stuff so that it should hopefully be relatively-ish painless?)

**Comment by BillLehecka** [comment]
Hooray! It works!

![IMG_4861](https://user-images.githubusercontent.com/33526260/189541807-63baa85a-9b1b-4ff3-9be3-ae3681f4366b.jpeg)

Thank you so much again. I even wrote a shortcut to switch from the Baseball to the Fantasy Football Scoreboard for optimum disappointment! :)
